### ISSUE TITLE
Positive Listening and Signalling 

### ISSUE THREAD

**Issue by richielo** [ToruOwO/marl-ae-comm#1]
Thank you for open sourcing your code. Just wondering if you could include your implementation for the the auxiliary losses of positive listening and signalling. 

Thank you!

**Comment by ToruOwO** [comment]
Hi,

I'm afraid as this moment we're maintaining the repo as-it-is. If you're
interested in implementing Eccles et al. method, I encourage you to reach
out to the original authors.

Best wishes,
Toru

**Comment by richielo** [comment]
Hello Toru,

No problem. Thank you for letting me know.

Cheers,
Richie
